export const allMarketData = [
  {
    name: "BTCUSDT",
    type: "Bitcoin",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "AXSUSDT",
    type: "Axie Infinity",
    amount: "$224",
    percentage: "-0.4%",
    isPositive: false,
  },
  {
    name: "ETHUSDT",
    type: "Ethereum",
    amount: "$24",
    percentage: "-3.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
  {
    name: "AXSUSDT",
    type: "Axie Infinity",
    amount: "$224",
    percentage: "-0.4%",
    isPositive: false,
  },
  {
    name: "ETHUSDT",
    type: "Ethereum",
    amount: "$24",
    percentage: "-3.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
  {
    name: "AXSUSDT",
    type: "Axie Infinity",
    amount: "$224",
    percentage: "-0.4%",
    isPositive: false,
  },
  {
    name: "ETHUSDT",
    type: "Ethereum",
    amount: "$24",
    percentage: "-3.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
  {
    name: "AXSUSDT",
    type: "Axie Infinity",
    amount: "$224",
    percentage: "-0.4%",
    isPositive: false,
  },
  {
    name: "ETHUSDT",
    type: "Ethereum",
    amount: "$24",
    percentage: "-3.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
  {
    name: "AXSUSDT",
    type: "Axie Infinity",
    amount: "$224",
    percentage: "-0.4%",
    isPositive: false,
  },
  {
    name: "ETHUSDT",
    type: "Ethereum",
    amount: "$24",
    percentage: "-3.4%",
    isPositive: false,
  },
  {
    name: "SOLUSDT",
    type: "Solana",
    amount: "$23,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "BNBUSDT",
    type: "Binance",
    amount: "$30,224",
    percentage: "+23.4%",
    isPositive: true,
  },
  {
    name: "ADAUSDT",
    type: "Cardano",
    amount: "$40,224",
    percentage: "-23.4%",
    isPositive: false,
  },
];

export const allTransactionsData = [
  {
    type: "Deposit",
    time: "11.23AM",
    amount: "+$23,224",
    status: "pending",
    isUp: true,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "Deposit",
    time: "11.23AM",
    amount: "+$23,224",
    status: "pending",
    isUp: true,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "Deposit",
    time: "11.23AM",
    amount: "+$23,224",
    status: "pending",
    isUp: true,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "Deposit",
    time: "11.23AM",
    amount: "+$23,224",
    status: "pending",
    isUp: true,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "Deposit",
    time: "11.23AM",
    amount: "+$23,224",
    status: "pending",
    isUp: true,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
  {
    type: "SANDUSDT",
    time: "11.23AM",
    amount: "-$724",
    status: "done",
    isUp: false,
  },
  {
    type: "DOGEUSDT",
    time: "11.23AM",
    amount: "+$3524",
    status: "done",
    isUp: true,
  },
  {
    type: "FTMUSDT",
    time: "11.23AM",
    amount: "-$524",
    status: "done",
    isUp: false,
  },
];
